/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Daos.ClaseDAO;
import Modelo.ClaseDto;
import Modelo.Tipos_de_Clases;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UTN
 */
public class GestionClases extends javax.swing.JInternalFrame {
    
    private ClaseDAO claseDAO;

    /**
     * Creates new form GestionClases
     */
    public GestionClases() {
        initComponents();
        claseDAO = new ClaseDAO();
        cargarTiposClases();
        cargarTodasLasClases();
    }
    
    private void cargarTiposClases() {
        FiltroClasesT.removeAllItems();
        FiltroClasesT.addItem("Todas");
        for (Tipos_de_Clases tipo : Tipos_de_Clases.values()) {
            FiltroClasesT.addItem(tipo.name());
        }
    }
    
    private void cargarTodasLasClases() {
        List<ClaseDto> clases = claseDAO.obtenerTodo();
        mostrarClasesEnTabla(clases);
    }
    
    private void mostrarClasesEnTabla(List<ClaseDto> clases) {
        DefaultTableModel modelo = (DefaultTableModel) TablaGestionClases.getModel();
        modelo.setRowCount(0);
        
        for (ClaseDto clase : clases) {
            Object[] fila = {
                clase.getId_clase(),
                clase.getTipo(),
                clase.getidEntrenador()
            };
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaGestionClases = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BtnEliminarClase = new javax.swing.JButton();
        BtnActualizarClase = new javax.swing.JButton();
        BtnAgregarClase = new javax.swing.JButton();
        BtnFiltrarClase = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FiltroClasesT = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        FiltroClasesID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FiltroClasesET = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(544, 410));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GYMPRIME");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TablaGestionClases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "TIPO DE CLASE", "ENTRENADOR"
            }
        ));
        jScrollPane1.setViewportView(TablaGestionClases);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnEliminarClase.setText("ELIMINAR");
        BtnEliminarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarClaseActionPerformed(evt);
            }
        });

        BtnActualizarClase.setText("ACTUALIZAR");
        BtnActualizarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarClaseActionPerformed(evt);
            }
        });

        BtnAgregarClase.setText("AGREGAR");
        BtnAgregarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarClaseActionPerformed(evt);
            }
        });

        BtnFiltrarClase.setText("FILTRAR");
        BtnFiltrarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiltrarClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnEliminarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnActualizarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgregarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnFiltrarClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnFiltrarClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnActualizarClase, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(BtnEliminarClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAgregarClase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Tipo de clase:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FiltroClasesT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("ID:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Entrenador:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiltroClasesT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiltroClasesID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiltroClasesET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FiltroClasesT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(FiltroClasesID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(FiltroClasesET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFiltrarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltrarClaseActionPerformed
        try {
            String idFiltro = FiltroClasesID.getText().trim();
            String tipoFiltro = FiltroClasesT.getSelectedItem().toString();
            String entrenadorFiltro = FiltroClasesET.getText().trim();
            
            List<ClaseDto> todas = claseDAO.obtenerTodo();
            
            if (!idFiltro.isEmpty()) {
                try {
                    int id = Integer.parseInt(idFiltro);
                    ClaseDto clase = claseDAO.buscar(id);
                    if (clase != null) {
                        java.util.ArrayList<ClaseDto> lista = new java.util.ArrayList<>();
                        lista.add(clase);
                        mostrarClasesEnTabla(lista);
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró la clase", "Información", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "ID inválido", "Error", JOptionPane.ERROR_MESSAGE);
                }
                return;
            }
            
            // Filtrar
            java.util.ArrayList<ClaseDto> filtradas = new java.util.ArrayList<>();
            for (ClaseDto c : todas) {
                boolean cumpleTipo = tipoFiltro.equals("Todas") || c.getTipo().equals(tipoFiltro);
                boolean cumpleEntrenador = entrenadorFiltro.isEmpty() || c.getidEntrenador().equals(entrenadorFiltro);
                if (cumpleTipo && cumpleEntrenador) {
                    filtradas.add(c);
                }
            }
            
            mostrarClasesEnTabla(filtradas);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al filtrar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnFiltrarClaseActionPerformed

    private void BtnEliminarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarClaseActionPerformed
        int filaSeleccionada = TablaGestionClases.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una clase para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar esta clase?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                int id = (Integer) TablaGestionClases.getValueAt(filaSeleccionada, 0);
                claseDAO.eliminar(id);
                JOptionPane.showMessageDialog(this, "Clase eliminada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarTodasLasClases();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnEliminarClaseActionPerformed

    private void BtnActualizarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarClaseActionPerformed
        JOptionPane.showMessageDialog(this, "Para actualizar, use los campos de filtro y luego modifique desde la base de datos directamente", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnActualizarClaseActionPerformed

    private void BtnAgregarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarClaseActionPerformed
        RegistroClases registro = new RegistroClases();
        this.getParent().add(registro);
        registro.setVisible(true);
    }//GEN-LAST:event_BtnAgregarClaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarClase;
    private javax.swing.JButton BtnAgregarClase;
    private javax.swing.JButton BtnEliminarClase;
    private javax.swing.JButton BtnFiltrarClase;
    private javax.swing.JTextField FiltroClasesET;
    private javax.swing.JTextField FiltroClasesID;
    private javax.swing.JComboBox<String> FiltroClasesT;
    private javax.swing.JTable TablaGestionClases;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
