/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Daos.EntrenadorDAO;
import Modelo.EntrenadorDto;
import Modelo.TiposEspecialidades;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UTN
 */
public class GestionarEntrenador extends javax.swing.JInternalFrame {
    
    private EntrenadorDAO entrenadorDAO;

    /**
     * Creates new form BuscarEntrenador
     */
    public GestionarEntrenador() {
        initComponents();
        entrenadorDAO = new EntrenadorDAO();
        cargarEspecialidades();
        cargarTodosLosEntrenadores();
    }
    
    private void cargarEspecialidades() {
        FiltroEntrenadorEP.removeAllItems();
        FiltroEntrenadorEP.addItem("Todas");
        for (TiposEspecialidades tipo : TiposEspecialidades.values()) {
            FiltroEntrenadorEP.addItem(tipo.name());
        }
    }
    
    private void cargarTodosLosEntrenadores() {
        List<EntrenadorDto> entrenadores = entrenadorDAO.obtenerTodo();
        mostrarEntrenadoresEnTabla(entrenadores);
    }
    
    private void mostrarEntrenadoresEnTabla(List<EntrenadorDto> entrenadores) {
        DefaultTableModel modelo = (DefaultTableModel) jTablaEntrenadores.getModel();
        modelo.setRowCount(0);
        
        for (EntrenadorDto entrenador : entrenadores) {
            Object[] fila = {
                entrenador.getId(),
                entrenador.getNombre(),
                entrenador.getContacto(),
                entrenador.getEspecialidad().name()
            };
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaEntrenadores = new javax.swing.JTable();
        BtnEliminarEntrenador = new javax.swing.JButton();
        BtnBuscarEntrenador = new javax.swing.JButton();
        BtnActualizarEntrenador = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FiltroEntrenadorID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FiltroEntrenadorNM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FiltroEntrenadorCT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FiltroEntrenadorEP = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GYMPRIME");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Entrenador "));

        jTablaEntrenadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CONTACTO", "ESPECIALIDAD"
            }
        ));
        jScrollPane1.setViewportView(jTablaEntrenadores);

        BtnEliminarEntrenador.setText("ELIMINAR");
        BtnEliminarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarEntrenadorActionPerformed(evt);
            }
        });

        BtnBuscarEntrenador.setText("BUSCAR");
        BtnBuscarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarEntrenadorActionPerformed(evt);
            }
        });

        BtnActualizarEntrenador.setText("ACTUALIZAR");
        BtnActualizarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarEntrenadorActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Nombre:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Contacto:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Especialidad:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FiltroEntrenadorEP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiltroEntrenadorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FiltroEntrenadorNM, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiltroEntrenadorCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FiltroEntrenadorEP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FiltroEntrenadorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiltroEntrenadorNM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiltroEntrenadorCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(FiltroEntrenadorEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnEliminarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnActualizarEntrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEliminarEntrenador, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(BtnBuscarEntrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnActualizarEntrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarEntrenadorActionPerformed
        try {
            String idFiltro = FiltroEntrenadorID.getText().trim();
            String nombreFiltro = FiltroEntrenadorNM.getText().trim();
            String especialidadFiltro = FiltroEntrenadorEP.getSelectedItem().toString();
            
            List<EntrenadorDto> todos = entrenadorDAO.obtenerTodo();
            
            if (!idFiltro.isEmpty()) {
                try {
                    int id = Integer.parseInt(idFiltro);
                    EntrenadorDto entrenador = entrenadorDAO.buscarEntrenadorPorId(id);
                    if (entrenador != null) {
                        java.util.ArrayList<EntrenadorDto> lista = new java.util.ArrayList<>();
                        lista.add(entrenador);
                        mostrarEntrenadoresEnTabla(lista);
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el entrenador", "Información", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "ID inválido", "Error", JOptionPane.ERROR_MESSAGE);
                }
                return;
            }
            
            // Filtrar por nombre y especialidad
            java.util.ArrayList<EntrenadorDto> filtrados = new java.util.ArrayList<>();
            for (EntrenadorDto e : todos) {
                boolean cumpleNombre = nombreFiltro.isEmpty() || e.getNombre().toLowerCase().contains(nombreFiltro.toLowerCase());
                boolean cumpleEspecialidad = especialidadFiltro.equals("Todas") || e.getEspecialidad().name().equals(especialidadFiltro);
                if (cumpleNombre && cumpleEspecialidad) {
                    filtrados.add(e);
                }
            }
            
            mostrarEntrenadoresEnTabla(filtrados);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnBuscarEntrenadorActionPerformed

    private void BtnEliminarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarEntrenadorActionPerformed
        int filaSeleccionada = jTablaEntrenadores.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un entrenador para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este entrenador?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                int id = (Integer) jTablaEntrenadores.getValueAt(filaSeleccionada, 0);
                entrenadorDAO.eliminar(id);
                JOptionPane.showMessageDialog(this, "Entrenador eliminado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarTodosLosEntrenadores();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnEliminarEntrenadorActionPerformed

    private void BtnActualizarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarEntrenadorActionPerformed
        int filaSeleccionada = jTablaEntrenadores.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un entrenador para actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Para actualizar, use los campos de filtro y luego modifique desde la base de datos directamente", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnActualizarEntrenadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarEntrenador;
    private javax.swing.JButton BtnBuscarEntrenador;
    private javax.swing.JButton BtnEliminarEntrenador;
    private javax.swing.JTextField FiltroEntrenadorCT;
    private javax.swing.JComboBox<String> FiltroEntrenadorEP;
    private javax.swing.JTextField FiltroEntrenadorID;
    private javax.swing.JTextField FiltroEntrenadorNM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaEntrenadores;
    // End of variables declaration//GEN-END:variables
}
