/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author UTN
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Clases = new javax.swing.JMenu();
        OpClases = new javax.swing.JMenuItem();
        Entrenadores = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        OpAgregarCliente = new javax.swing.JMenuItem();
        Pagos = new javax.swing.JMenu();
        OpPagos = new javax.swing.JMenuItem();
        Usuarios = new javax.swing.JMenu();
        OpUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Clases.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clases.setText("Clases");

        OpClases.setText("Clases");
        OpClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpClasesActionPerformed(evt);
            }
        });
        Clases.add(OpClases);

        jMenuBar1.add(Clases);

        Entrenadores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Entrenadores.setText("Entrenadores");

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Entrenadores.add(jMenuItem1);

        jMenuBar1.add(Entrenadores);

        Clientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clientes.setText("Clientes");

        OpAgregarCliente.setText("Agregar");
        OpAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpAgregarClienteActionPerformed(evt);
            }
        });
        Clientes.add(OpAgregarCliente);

        jMenuBar1.add(Clientes);

        Pagos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pagos.setText("Pagos");

        OpPagos.setText("Pago");
        OpPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpPagosActionPerformed(evt);
            }
        });
        Pagos.add(OpPagos);

        jMenuBar1.add(Pagos);

        Usuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Usuarios.setText("Usuarios");

        OpUsuarios.setText("Culsultar");
        OpUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpUsuariosActionPerformed(evt);
            }
        });
        Usuarios.add(OpUsuarios);

        jMenuBar1.add(Usuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpAgregarClienteActionPerformed
        AgregarCliente agregarCliente = new AgregarCliente();
        Escritorio.add(agregarCliente);
        agregarCliente.setVisible(true);
        
    }//GEN-LAST:event_OpAgregarClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AgregarEntrenador  agregarentrenador = new  AgregarEntrenador();
        Escritorio.add(agregarentrenador);
       agregarentrenador.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void OpClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpClasesActionPerformed
        Clases clase = new Clases();
        Escritorio.add(clase);
        clase.setVisible(true);
    }//GEN-LAST:event_OpClasesActionPerformed

    private void OpPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpPagosActionPerformed
        Pagos pago = new Pagos();
        Escritorio.add(pago);
        pago.setVisible(true);
    }//GEN-LAST:event_OpPagosActionPerformed

    private void OpUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpUsuariosActionPerformed
         FUsuarios usuario = new FUsuarios();
        Escritorio.add(usuario);
       usuario.setVisible(true);
    }//GEN-LAST:event_OpUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clases;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenu Entrenadores;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem OpAgregarCliente;
    private javax.swing.JMenuItem OpClases;
    private javax.swing.JMenuItem OpPagos;
    private javax.swing.JMenuItem OpUsuarios;
    private javax.swing.JMenu Pagos;
    private javax.swing.JMenu Usuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
